// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizPlatform.DataAccess.Data;

namespace QuizPlatform.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211019151919_fixes")]
    partial class fixes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuizPlatform.Core.Domain.QuestionManagment.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af85376b-aa45-4f0b-8f91-0549b3118060"),
                            Name = "Music"
                        },
                        new
                        {
                            Id = new Guid("c27aba67-3fbc-4259-b458-56da8d98ad0a"),
                            Name = "History"
                        });
                });

            modelBuilder.Entity("QuizPlatform.Core.Domain.QuestionManagment.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("QuestionTypeGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("QuestionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TimerInSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("WithTimer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QuizPlatform.Core.Domain.QuestionManagment.QuestionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("QuestionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bd2074c-a652-4905-a516-22f4336a86d6"),
                            Name = "With exact answer"
                        },
                        new
                        {
                            Id = new Guid("b1e33469-245c-4dd6-87fd-c2ba0427b06b"),
                            Name = "With answer options"
                        });
                });

            modelBuilder.Entity("QuizPlatform.Core.Domain.QuestionManagment.Question", b =>
                {
                    b.HasOne("QuizPlatform.Core.Domain.QuestionManagment.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("QuizPlatform.Core.Domain.QuestionManagment.QuestionType", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeId");

                    b.Navigation("Category");

                    b.Navigation("QuestionType");
                });
#pragma warning restore 612, 618
        }
    }
}
